### ISSUE TITLE
NullPointerException when parsing tiny C files 

### ISSUE THREAD

**Issue by jfarmer20** [jplag/JPlag#240]
Analysing tiny Java files with command line `java -jar jplag-3.0.0-SNAPSHOT-jar-with-dependencies.jar ./subTestJava -l java9` works perfectly.  
Analysing similar tiny C files with command line `java -jar jplag-3.0.0-SNAPSHOT-jar-with-dependencies.jar ./subTestC -l cpp` produces the following error: 

```  
Initialized language C/C++ Scanner [basic markup]
JPlag initialized
java.lang.NullPointerException
        at de.jplag.cpp.Scanner.scan(Scanner.java:19)
        at de.jplag.cpp.Language.parse(Language.java:64)
        at de.jplag.Submission.parse(Submission.java:162)
        at de.jplag.SubmissionSet.parseSubmissions(SubmissionSet.java:153)
        at de.jplag.SubmissionSet.parseAllSubmissions(SubmissionSet.java:98)
        at de.jplag.SubmissionSet.<init>(SubmissionSet.java:44)
        at de.jplag.SubmissionSetBuilder.mapFileNamesToSubmissions(SubmissionSetBuilder.java:129)
        at de.jplag.SubmissionSetBuilder.buildSubmissionSet(SubmissionSetBuilder.java:64)
        at de.jplag.JPlag.run(JPlag.java:48)
        at de.jplag.CLI.main(CLI.java:57)
Error: Unknown exception during parsing of submission "Q2-108_CircleLine.c"  
```  
Find my tiny C files enclosed: 
[subTestC.zip](https://github.com/jplag/JPlag/files/7611555/subTestC.zip)

**Comment by tsaglam** [comment]
I pushed a hotfix with 20a882e, this should have resolved the issue. If it doesn't, please let me know!

**Comment by jfarmer20** [comment]
NullPointerException is not thrown anymore. But the tiny C files are still not parsed. When I call the hotfixed jplag-tool with arguments `./subTestC -l cpp`, I get the following CLI-output:  

```  
Initialized language C/C++ Scanner [basic markup]
JPlag initialized
Total time for comparing submissions: 0 sec
Writing report...
Report exported to C:\Users\jfarm\IdeaProjects\JPlag\result

Process finished with exit code 0  
```  

It works fine with similar tiny Java files ( `./subTestJava -l java9`). Find them enclosed:  

```  
Initialized language Javac 1.9+ based AST plugin
JPlag initialized
Comparing Test1.java-Test2.java: 60.869564
Comparing Test1.java-Test3.java: 100.0
Comparing Test2.java-Test3.java: 60.869564
Total time for comparing submissions: 0 sec
Writing report...
Writing matches: 30%
Writing matches: 65%
Writing matches: 100%
Report exported to C:\Users\jfarm\IdeaProjects\JPlag\result

Process finished with exit code 0
``` 
[subTestJava.zip](https://github.com/jplag/JPlag/files/7613175/subTestJava.zip)

**Comment by tsaglam** [comment]
Programs that are shorter than the min token match will be ignored. The Java frontend uses a different min token match than the C/C++ frontend. If you run JPlag with `./subTestC -l cpp -t 9` it will also accept the C code.

However, It should actually tell you that this is the case, but obiously it doesn't (relates to #157). This should be fixed!

**Comment by tsaglam** [comment]
I fixed the messages with d276a23 and 3d1cee0, the CLI should now display the proper error messages!

**Comment by jfarmer20** [comment]
Thanks a lot! It now works perfectly :-)
